### ISSUE TITLE
Instructions in README lead to error.

### ISSUE THREAD

**Issue by r3drock** [tota-dart/tota#10]
I did follow the instructions until tota build.
I get the the Following output:
```sh=
$ tota build
Deleting public directory
Generating static files...             0.2s
Creating archive pages
Template not found: /home/r3drock/blog/templates/archive.mustache
```

**Comment by izolate** [comment]
Hi @r3drock, thanks for bringing this bug to my attention. I'm working towards a `1.0.0` release, so I apologise for any inconsistencies.

I've updated the starting template, so please remove your directory contents and run `tota init` again.

That should fix it, but feel free to reopen this issue if you have further problems.

***

Also, please note that as of version [0.6.1](https://pub.dev/packages/tota#-changelog-tab-) the use of `.env` files are deprecated to prioritise running in an automated/CI context. You have 2 options now:

1) Run a command with the desired config explicity prefixed as environment variables
```bash
TOTA_TITLE="example" TOTA_URL="example.com" tota build
```

2) Use your `.env` file with a CLI dotenv loader like [dotenv-cli](https://www.npmjs.com/package/dotenv-cli) (Node)

```bash
dotenv tota build
```
